# Generated by Django 3.2 on 2024-03-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_information', '0002_remove_section_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='performance_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='quartery_assessment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='written_work',
            field=models.IntegerField(default=0),
        ),
    ]
