# Generated by Django 3.2 on 2024-04-24 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_information', '0003_auto_20240317_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEncode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grading_period', models.CharField(choices=[('FIRST_GRADING', 'First Grading'), ('SECOND_GRADING', 'Second Grading'), ('THIRD_GRADING', 'Third Grading'), ('FOURTH_GRADING', 'Fourth Grading')], default='FIRST_GRADING', max_length=255)),
                ('is_enable', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('grading_period', 'is_enable')},
            },
        ),
    ]
