# Generated by Django 3.2 on 2024-04-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20240415_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
