# Generated by Django 3.2 on 2024-03-13 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('class_information', '0002_remove_section_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_level', models.CharField(choices=[('GRADE 7', 'GRADE 7'), ('GRADE 8', 'GRADE 8'), ('GRADE 9', 'GRADE 9'), ('GRADE 10', 'GRADE 10'), ('GRADE 11', 'GRADE 11'), ('GRADE 12', 'GRADE 12')], default='GRADE 7', max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_information.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
