# Generated by Django 3.2 on 2024-03-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0005_academicyear'),
        ('registration', '0003_registration_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_record.academicyear'),
        ),
    ]
