# Generated by Django 3.2 on 2024-03-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('academic_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.teacher'),
            preserve_default=False,
        ),
    ]
