# Generated by Django 3.2 on 2024-03-13 15:31

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('academic_record', '0002_assessment_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='grade',
            name='marks',
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
