# Generated by Django 3.2 on 2024-03-16 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0003_auto_20240313_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grading_period',
            field=models.CharField(choices=[('First Grading', 'First Grading'), ('Second Grading', 'Second Grading'), (
                'Third Grading', 'Third Grading'), ('Fourth Grading', 'Fourth Grading')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
