# Generated by Django 3.2 on 2024-03-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0006_auto_20240316_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
