# Generated by Django 3.2 on 2024-03-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0007_academicyear_remarks'),
    ]

    operations = [
    ]
