# Generated by Django 3.2 on 2024-03-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0011_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='academic_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='academic_record.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('GRADE 7', 'Grade 7')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
