# Generated by Django 3.2 on 2024-03-19 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0013_auto_20240320_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attend',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 23, 0, 3, 76823, tzinfo=utc)),
        ),
    ]
