# Generated by Django 3.2 on 2024-03-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0015_alter_attendance_date_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='grading_period',
            field=models.CharField(choices=[('FIRST_GRADING', 'First Grading'), ('SECOND_GRADING', 'Second Grading'), ('THIRD_GRADING', 'Third Grading'), ('FOURTH_GRADING', 'Fourth Grading')], default='FIRST_GRADING', max_length=255),
        ),
    ]
