# Generated by Django 3.2 on 2024-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0016_assessment_grading_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='task_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('PROJECT', 'Project'), ('EXAM', 'Exam')], default='ASSIGNMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('WRITTEN_WORKS', 'Written Works'), ('PERFORMANCE_TASK', 'Performance Task'), ('QUARTERLY_ASSESSMENT', 'Quarterly Assessment')], default='WRITTEN_WORKS', max_length=50),
        ),
    ]
