# Generated by Django 3.2 on 2024-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0017_auto_20240323_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date_attend',
            new_name='time_in',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
