# Generated by Django 3.2 on 2024-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0022_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='attendance_date',
        ),
    ]
