# Generated by Django 3.2 on 2024-04-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('academic_record', '0024_auto_20240327_1000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together={('assessment', 'student')},
        ),
    ]
