# Generated by Django 3.2 on 2024-04-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0025_alter_studentassessment_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
