# Generated by Django 3.2 on 2024-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0026_delete_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='first_grading_dealine',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='fourth_grading_dealine',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='second_grading_dealine',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='third_grading_dealine',
            field=models.DateField(null=True),
        ),
    ]
