# Generated by Django 3.2 on 2024-04-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0027_auto_20240424_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Assessment Name'),
        ),
    ]
