# Generated by Django 3.2 on 2024-04-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20240410_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='is_new_user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_new_user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_new_user',
        ),
    ]
