# Generated by Django 3.2 on 2024-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
