# Generated by Django 3.2 on 2024-04-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20240410_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
    ]
