# Generated by Django 3.2 on 2024-03-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20240306_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='kids', to='user_profile.Student'),
        ),
    ]
