# Generated by Django 3.2 on 2024-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20240307_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='kids', to='user_profile.Student'),
        ),
        migrations.DeleteModel(
            name='ParentStudent',
        ),
    ]
