# Generated by Django 3.2 on 2024-03-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appicon',
            name='delete_remarks',
        ),
        migrations.RemoveField(
            model_name='appicon',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='appicon',
            name='deleted_by_id',
        ),
        migrations.RemoveField(
            model_name='appicon',
            name='update_remarks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete_remarks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_by_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_remarks',
        ),
    ]
